export const TYPES = {
	REGISTER_DEVICE: "@app/REGISTER_DEVICE",
	REGISTER_DEVICE_SUCCESS: "@app/REGISTER_DEVICE_SUCCESS",

	REGISTER_MULTIPLE: "@app/REGISTER_MULTIPLE",
	REGISTER_MULTIPLE_SUCCESS: "@app/REGISTER_MULTIPLE_SUCCESS",

	UPDATE_DEVICE: "@app/UPDATE_DEVICE",
	UPDATE_DEVICE_SUCCESS: "@app/UPDATE_DEVICE_SUCCESS",

	DELETE_DEVICE_ERROR: "@app/DELETE_DEVICE_ERROR",
	DELETE_DEVICE_SUCCESS: "@app/DELETE_DEVICE_SUCCESS",
	DELETE_DEVICE: "@app/DELETE_DEVICE",
};
